spring:
   application:
      name: cfng-config
   profiles:
      active: native, local
   security:
      user:
         name: cfng-config-server
         password: cfng-config-client
   cloud:
      loadbalancer.ribbon.enabled: false   
      config:
         allowOverride: false
         server:
            bootstrap: true
            native.location.search-locations: file:./config/ #add valid path here
            overrides: # Shared configuration
# Service name in eureka
               cfng.services.name:
                  api: http://CFNG-API
                  auth: http://cfng-auth
                  backend: http://CFNG
                  access-management: http://cfng-access-management
                  event: http://cfng-event
                  passphrase-manager: http://cfng-passphrase-manager
                  messagerie: http://SM
# Eureka configuration
               eureka:
                  instance:
                     leaseRenewalIntervalInSeconds: 5
                     lease-expiration-duration-in-seconds: 5
                     preferIpAddress: false
                  client:
                     fetch-registry: true
                     registry-fetch-interval-seconds: 5

# Sleuth configuration
               spring.sleuth:
                  sampler.percentage: 1.0
                  web.skip-pattern: (^cleanup.*)
# Feign configuration
               feign:
                  client:
                     config:
                        default:
                           connectTimeout: ${rest.timeout}
                           readTimeout: ${rest.timeout}
# Ribbon configuration
               ribbon:
                  ReadTimeout: ${rest.timeout}
                  ConnectTimeout: ${rest.timeout}
                  OkToRetryOnAllOperations: true
                  MaxAutoRetries: 1
                  MaxAutoRetriesNextServer: 1
# Mail configuration
               spring.mail:
                  default-encoding: UTF-8
                  host: relaissmtp.almerys.local
                  port: 25
                  from: noreply-beidys@be-ys.com
                  username: null
                  password: null
                  properties:
                     mail:
                        smtp:
                           auth: false
                           ssl:
                              enable: false
                           starttls:
                              enable: false
                  protocol: smtp
                  test-connection: true

eureka:
   server:
      host: 192.168.50.10
      port: 8761
   instance:
      hostname: master
      leaseRenewalIntervalInSeconds: 5
      lease-expiration-duration-in-seconds: 5
      preferIpAddress: false
   client:
      fetch-registry: true
      registry-fetch-interval-seconds: 5
      service-url:
         defaultZone: http://192.168.50.10:8761/eureka

logging.level:
   root: info
   com.almerys: info
   org.springframework:
      security: info
      cloud.sleuth: info
   com.netflix.discovery:
      DiscoveryClient: OFF
      shared.transport.decorator: OFF
      shared.resolver.aws.ConfigClusterResolver: OFF
      
rest.timeout: 30000
